update ci

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -72,60 +72,60 @@ jobs:
           cp ${{ env.REPORTING_JAR_NAME }} ./reporting/app.jar
           cp ${{ env.REPORTING_JAR_NAME }} ./search/app.jar
 
-      - name: Log in to Docker Hub
-        uses: docker/login-action@v2
-        with:
-          username: ${{ secrets.DOCKER_USERNAME }}
-          password: ${{ secrets.DOCKER_PASSWORD }}
+      # - name: Log in to Docker Hub
+      #   uses: docker/login-action@v2
+      #   with:
+      #     username: ${{ secrets.DOCKER_USERNAME }}
+      #     password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Build and Push Docker Images
-        run: |
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_discovery:latest -f ./discovery/DockerFile ./discovery --push
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_authentication:latest -f ./authentication/DockerFile ./authentication --push
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_gateway:latest -f ./gateway/DockerFile ./gateway --push
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_user:latest -f ./user/DockerFile ./user --push
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_product:latest -f ./product/DockerFile ./product --push
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_payment:latest -f ./payment/DockerFile ./payment --push
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_reporting:latest -f ./reporting/DockerFile ./reporting --push
-          docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_search:latest -f ./search/DockerFile ./search --push
+      # - name: Build and Push Docker Images
+      #   run: |
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_discovery:latest -f ./discovery/DockerFile ./discovery --push
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_authentication:latest -f ./authentication/DockerFile ./authentication --push
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_gateway:latest -f ./gateway/DockerFile ./gateway --push
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_user:latest -f ./user/DockerFile ./user --push
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_product:latest -f ./product/DockerFile ./product --push
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_payment:latest -f ./payment/DockerFile ./payment --push
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_reporting:latest -f ./reporting/DockerFile ./reporting --push
+      #     docker buildx build --platform linux/amd64,linux/arm64 --build-arg JAR_FILE=app.jar -t amiril/kalado_search:latest -f ./search/DockerFile ./search --push
 
 
-      - name: Copy docker-compose.yml to server
-        uses: appleboy/scp-action@v0.1.0
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          password: ${{ secrets.SSH_PASSWORD }}
-          source: "docker-compose.yml"
-          target: "/home/kalado/repos/Kalado-Backend"
+      # - name: Copy docker-compose.yml to server
+      #   uses: appleboy/scp-action@v0.1.0
+      #   with:
+      #     host: ${{ secrets.SSH_HOST }}
+      #     username: ${{ secrets.SSH_USERNAME }}
+      #     password: ${{ secrets.SSH_PASSWORD }}
+      #     source: "docker-compose.yml"
+      #     target: "/home/kalado/repos/Kalado-Backend"
 
-      - name: Deploy with SSH
-        uses: appleboy/ssh-action@v0.1.7
-        with:
-          host: ${{ secrets.SSH_HOST }}
-          username: ${{ secrets.SSH_USERNAME }}
-          password: ${{ secrets.SSH_PASSWORD }}
-          script: |
-            cd //home/kalado/repos/Kalado-Backend
-            docker compose down
-            docker compose pull
-            docker compose up -d
-            max_retries=5
-            retries=0
-            while [ $retries -lt $max_retries ]; do
-              echo "Checking service status... Attempt $((retries + 1))"
-              status=$(docker compose ps --services --filter "status=running" | wc -l)
-              total_services=$(docker compose ps --services | wc -l)
-              if [ "$status" -eq "$total_services" ]; then
-                echo "All services are up!"
-                break
-              fi
-              echo "Not all services are up!"
-              retries=$((retries + 1))
-              sleep 10
-              docker compose up -d
-            done
-            if [ $retries -eq $max_retries ]; then
-              echo "Some services failed to start after $max_retries attempts."
-              exit 1
-            fi
+      # - name: Deploy with SSH
+      #   uses: appleboy/ssh-action@v0.1.7
+      #   with:
+      #     host: ${{ secrets.SSH_HOST }}
+      #     username: ${{ secrets.SSH_USERNAME }}
+      #     password: ${{ secrets.SSH_PASSWORD }}
+      #     script: |
+      #       cd //home/kalado/repos/Kalado-Backend
+      #       docker compose down
+      #       docker compose pull
+      #       docker compose up -d
+      #       max_retries=5
+      #       retries=0
+      #       while [ $retries -lt $max_retries ]; do
+      #         echo "Checking service status... Attempt $((retries + 1))"
+      #         status=$(docker compose ps --services --filter "status=running" | wc -l)
+      #         total_services=$(docker compose ps --services | wc -l)
+      #         if [ "$status" -eq "$total_services" ]; then
+      #           echo "All services are up!"
+      #           break
+      #         fi
+      #         echo "Not all services are up!"
+      #         retries=$((retries + 1))
+      #         sleep 10
+      #         docker compose up -d
+      #       done
+      #       if [ $retries -eq $max_retries ]; then
+      #         echo "Some services failed to start after $max_retries attempts."
+      #         exit 1
+      #       fi
